### ISSUE TITLE
website-interactions

### ISSUE THREAD

**Issue by Sayed94h** [Sayed94h/comments-on-website#7]
### Task A: HTML

- [x] Created many DOM elements for rendering comments to the users screen

### Task C: CSS

- [x] Styled the created DOM elements

### Task D: JavaScript

- [x] Created four routes
- [x] Created four handlers for the four routes to save, display, edit and delete comments
- [x] Wrote four functions for fetching data from backend

### Task E: Project planning

- [x] Wrote what I did in this part
- [x] Wrote more about the project in README file
- [x] Created PR, issues
